apiVersion: v1
kind: Secret
metadata:
  name: pod-watch-secrets
  namespace: kubernetes-pod-watch
type: Opaque
data:
  # Base64 encoded values
  # Empty password for postgres user
  DB_PASSWORD: ""
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzQGhvc3QuZG9ja2VyLmludGVybmFsOjU0MzIva3ViZXJuZXRlc19tb25pdG9yP3NzbG1vZGU9ZGlzYWJsZQ==  # "postgresql://postgres@host.docker.internal:5432/kubernetes_monitor?sslmode=disable" in base64
